version: '3.1'

networks:
  app-network:
    driver: bridge

services:
  mongo:
    image: mongo:6.0.1
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor